if: tag IS blank

language: go

branches:
  only:
    - master
    - dev
    - ci-cd-windows-origin

install: true

jobs:
  include:
    - name: linux
      os: linux
      dist: xenial
      sudo: required

      # before_install:
      # - go get gopkg.in/olivere/elastic.v7
      # - go get github.com/appbaseio/abc || true
      # - mkdir private
      # - git clone https://$PAT@github.com/appbaseio-confidential/abc-import private

      script:
        - go build -tags 'oss' -o "abc-linux" ./cmd/abc/...

      before_deploy:
        - zip -r abc-linux.zip abc-linux
        - export TRAVIS_TAG="preview"

      deploy:
        provider: releases
        api_key: $PAT
        skip_cleanup: true
        file: abc-linux.zip
        draft: true
        on:
          all_branches: true

    - name: macos
      os: osx
      osx_image: xcode9.4

      # before_install:
      #   - go get gopkg.in/olivere/elastic.v7
      #   - go get github.com/appbaseio/abc || true
      #   - mkdir private
      #   - git clone https://$PAT@github.com/appbaseio-confidential/abc-import private

      script:
        - go build -tags 'oss' -o "abc-darwin" ./cmd/abc/...

      before_deploy:
        - zip -r abc-darwin.zip abc-darwin
        - export TRAVIS_TAG="preview"

      deploy:
        provider: releases
        api_key: $PAT
        skip_cleanup: true
        file: abc-darwin.zip
        draft: true
        on:
          all_branches: true

    - name: windows
      os: windows

      # before_install:
      #   - go get gopkg.in/olivere/elastic.v7
      #   - go get github.com/appbaseio/abc || true
      #   - mkdir private
      #   - git clone https://$PAT@github.com/appbaseio-confidential/abc-import private

      script:
        - go build -tags 'oss' -o "abc-windows" ./cmd/abc/...

      before_deploy:
        - 7z a abc-windows.zip abc-windows
        - export TRAVIS_TAG="preview"

      deploy:
        provider: releases
        api_key: $PAT
        skip_cleanup: true
        file: abc-windows.zip
        draft: true
        on:
          all_branches: true
