name: ABC build

on:
  release:
    types: [ published ]
  

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - 
        name: Get Version
        id: get_version
        # You may pin to the exact commit or the version.
        # uses: battila7/get-version-action@90eb8fc70f6dfcf3f9b95ed8f164d2c05038e729
        uses: battila7/get-version-action@v2.2.1
    -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
        name: Build and push tagged image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ format('appbaseio/abc:{0}', steps.get_version.outputs.version) }}
    -
        name: Build and push latest image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: appbaseio/abc:latest