name: ABC package builder

on:
  release:
    types: [published]


jobs:
  packer:
    strategy:
      matrix:
        os: ['linux']
    runs-on: ubuntu-latest
    steps:

      - name : clone ABC 
        uses: actions/checkout@v2
        with:
          path: abc

      - name: Go environment
        uses: actions/setup-go@v2.1.3
        with:
          go-version: 1.16.2

      - name: Show directory before
        run: cd abc && ls ./
        
      - name: Package Linux
        run: cd abc && ls -l && go build -o "abc-${{matrix.os}}-${{github.event.release.tag_name}}" -tags 'oss' ./cmd/abc/...
      
      - name: show afer 
        run: cd abc && ls -la && ls -la ./cmd/abc/

      - name: Zip
        run: apt update && 